// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat.post').default>>>>
    }
    '/api/chats/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chats/[id]/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chats/[id]/index.get').default>>>>
    }
    '/api/chats/:id/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chats/[id]/messages.get').default>>>>
    }
    '/api/chats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chats/index.get').default>>>>
    }
    '/api/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/config.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/config.post').default>>>>
    }
    '/api/database/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/database/stats.get').default>>>>
    }
    '/api/discover': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/discover.get').default>>>>
    }
    '/api/images': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images.post').default>>>>
    }
    '/api/models': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/models.get').default>>>>
    }
    '/api/search': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search.post').default>>>>
    }
    '/api/suggestions': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/suggestions.post').default>>>>
    }
    '/api/test-db': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test-db.get').default>>>>
    }
    '/api/test-providers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test-providers.get').default>>>>
    }
    '/api/uploads': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/uploads.post').default>>>>
    }
    '/api/videos': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/videos.post').default>>>>
    }
    '/api/weather': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/weather.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}