// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 07:58:15 10/6/2025
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/workspace/Projects/Intellix/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/workspace/Projects/Intellix/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/workspace/Projects/Intellix/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/workspace/Projects/Intellix/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/workspace/Projects/Intellix/plugins/**/*.{js,ts,mjs}","D:/workspace/Projects/Intellix/composables/**/*.{js,ts,mjs}","D:/workspace/Projects/Intellix/utils/**/*.{js,ts,mjs}","D:/workspace/Projects/Intellix/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/workspace/Projects/Intellix/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/workspace/Projects/Intellix/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/workspace/Projects/Intellix/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;